services:
  mysql:
    image: mysql:5.7
    container_name: coffee-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: coffee_vending_system
    ports:
      - "3307:3306"
    restart: unless-stopped

  app:
    build: .
    container_name: coffee-app
    depends_on:
      - mysql
    environment:
      DB_URL: jdbc:mysql://mysql:3306/coffee_vending_system?useSSL=false&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: rootpass
    restart: unless-stopped